# Generated by Django 3.2.2 on 2021-05-12 11:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
                ('picture', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/sd2001/image/upload/v1620818730/temp_cvo0h5.jpg', max_length=255, null=True, verbose_name='image')),
                ('github', models.CharField(max_length=30)),
                ('live', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
