# Generated by Django 3.2.2 on 2021-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210512_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='picture',
            new_name='image',
        ),
    ]
