# Generated by Django 3.2.2 on 2021-06-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210603_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='live',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
